version: '3.9'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${password}
  db_booking:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - test_postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${admin}
      - POSTGRES_PASSWORD=${admindb}
      - POSTGRES_DB=${testdb}

volumes:
  redis:
  test_postgres-data: