version: '3.9'
services:
  web:
    build: ./
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./MeetBooking/:/usr/src/MeetBooking/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  db_booking:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_booking:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
volumes:
  redis:
  db_booking:
