version: '3.7'
services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:${DJANGO_PORT} meet_booking.wsgi
    env_file:
      - ./.env
    expose:
      - ${DJANGO_PORT}
    depends_on:
      - db_booking
    volumes:
      - staticfiles:/home/MeetBooking/staticfiles/
  redis:
    image: redis:6.2.6
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  db_booking:
    image: postgres:14.0
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_booking:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    image: nginx:1.21.3
    ports:
      - ${DJANGO_PORT}:${NGINX_OUTPUT_PORT}
    environment:
      - DJANGO_PORT=${DJANGO_PORT}
      - NGINX_OUTPUT_PORT=${NGINX_OUTPUT_PORT}
    volumes:
      - ./static:/home/MeetBooking/static
      - staticfiles:/home/MeetBooking/staticfiles/
      - ./configs/nginx.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - web

volumes:
  db_booking:
  staticfiles:
    name: staticfiles
