version: '3.7'
services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:${DJANGO_PORT} meet_booking.wsgi
    env_file:
      - ./.env
    expose:
      - ${DJANGO_PORT}
    depends_on:
      - db_booking
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  db_booking:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_booking:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    build: ./nginx
    ports:
      - ${DJANGO_PORT}:80
    volumes:
      - /Users/maxim/Desktop/MeetBooking/staticfiles:/home/MeetBooking/staticfiles
    depends_on:
      - web

volumes:
  redis:
  db_booking:
  web:
  nginx:
