version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=123
  db_booking:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_booking:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test
volumes:
  redis:
  db_booking: