# Generated by Django 3.2.7 on 2021-09-24 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_count', models.IntegerField(verbose_name='Всего мест')),
                ('projector', models.BooleanField(verbose_name='Наличие проектора')),
                ('tv', models.BooleanField(verbose_name='ТВ')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('room_number', models.IntegerField(unique=True, verbose_name='Номер кабинета')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('start_time', models.TimeField(verbose_name='Время начала мероприятия')),
                ('end_time', models.TimeField(verbose_name='Время окончания мероприятия')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_cabinet', to='booking.cabinet', verbose_name='Номер кабинета')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_sponsor', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('visitors', models.ManyToManyField(blank=True, related_name='event_visitors', to=settings.AUTH_USER_MODEL, verbose_name='Посетители')),
            ],
            options={
                'unique_together': {('cabinet', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
