# Generated by Django 3.2.7 on 2021-09-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.ManyToManyField(related_name='event_time', to='booking.TimeBooking', verbose_name='Время начала мероприятия'),
        ),
    ]
