name: Code cheaker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running flake8
        run: flake8 .
        